### PR TITLE
Fix graph dependsOn 

### LINKED ISSUE #721: `dependsOn` option failed with brew upgrade
There is some issue when doing brew upgrade: https://github.com/Homebrew/homebrew-core/pull/39628

`.terrahub.yml` template:
```
      project:
        name: terrahub-demo
        code: abcd1234
      vpc_component:
        name: vpc
        root: ./vpc
      subnet_component:
        name: subnet
        root: ./subnet
        dependsOn:
          - ./vpc
```

error:
```
==> /usr/local/Cellar/terrahub/0.2.54/bin/terrahub graph
❌ Couldn't find dependency 'vpc'
Error: terrahub: failed
```

### PR DESCRIPTION
**Pull request by const-andreyLu**
## Description

Fixes #721 

## Type of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## How Has This Been Tested?

- [ ]  thub graph

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/config-loader.js [hunk 1]
```diff
@@ -218,15 +218,13 @@ class ConfigLoader {
...
-        this._config[ConfigLoader.buildComponentHash(root)] = cfg;
+
         delete this._rootConfig[key];
-      }
-    });
 
-    Object.keys(this._config).forEach(module => {
-      this._config[module] = extend({}, [this._componentDefaults(), this._rootConfig, this._config[module]]);
+        this._processComponentConfig(cfg, root);
+        this._config[ConfigLoader.buildComponentHash(root)] = extend({}, [this._componentDefaults(), this._rootConfig, cfg]);
```
Comment (Leichtwind) [inline src/config-loader.js]:
```suggestion
        const hash = ConfigLoader.buildComponentHash(root);
        this._config[hash] = extend({}, [this._componentDefaults(), this._rootConfig, cfg]);
```

File: src/config-loader.js [hunk 2]
```diff
@@ -298,6 +266,45 @@ class ConfigLoader {
     }
   }
 
+
+  /**
+   * @param config {Array}
```
Comment (Leichtwind) [inline src/config-loader.js]:
```suggestion
   * @param config {Object}
```

File: src/config-loader.js [hunk 3]
```diff
@@ -298,6 +266,45 @@ class ConfigLoader {
     }
   }
 
+
```
Comment (Leichtwind) [inline src/config-loader.js]:
```suggestion
```
