### PR TITLE
fix for deleteComponent, code improvement

### LINKED ISSUE #465: Add user friendly and informative message when trying to delete inexistent component
## Steps to Reproduce

1. Create terrahub component A
2. Run the command `terrahub component -n A -D`
3. Run the command `terrahub component -n A -D` once again 

## Expected Behavior

It is expected to have an user friendly and informative message when trying to delete inexistent component

## Actual Behavior
Error is displayed

### PR DESCRIPTION
**Pull request by KanoniPan**
## Description

Fixes #465 

## Type of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/commands/component.js [hunk 1]
```diff
@@ -60,7 +60,7 @@ class ComponentCommand extends AbstractCommand {
         if (!answer) {
           return Promise.reject('Action aborted');
         } else {
-          return Promise.all(names.map(it => this._deleteComponent(it))).then(() => 'Done');
+          return Promise.all(names.map(it => this._deleteComponent(it))).then(() => Promise.resolve());
```
Comment (ddimitrioglo) [inline src/commands/component.js]: no message an the end of the command

Comment (ddimitrioglo) [reply src/commands/component.js]: at line 71 there is 'Done'

Comment (ddimitrioglo) [reply src/commands/component.js]: at 75 also there is 'Done'
