### PR TITLE
Fix spawn workers count 

### LINKED ISSUE #808: Thread limitation doesn't work for `terrahub build` command
## Describe the Bug

Thread limitation doesn't work for `terrahub build` command

## To Reproduce

1. Go to Jenkins
2. Run `terrahub build` on a big project (e.g. terrahub api)
3. Observe number of threads (expected: 8 at a time; real: all of them started in the same moment)

### PR DESCRIPTION
**Pull request by const-andreyLu**
## Description

Fixes #808

## Type of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## How Has This Been Tested?

- [x] [jenkins-job](https://jenkins.mitocgroup.com/job/mitocgroup-terrahub-api/2439/console)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/helpers/distributors/thread-distributor.js [hunk 1]
```diff
@@ -217,6 +223,19 @@ class ThreadDistributor extends AbstractDistributor {
...
+   * Returns worker spawn file name
+   * @param {Object} worker
+   * @return {String}
+   * @private
+   */
+  _getWorkerName(worker) {
+    const fileName = worker.process.spawnargs[1];
+    const extension = path.extname(fileName);
+
+    return  path.basename(fileName,extension);
```
Comment (eistrati) [inline src/helpers/distributors/thread-distributor.js]: missing space after comma

Comment (const-andreyLu) [reply src/helpers/distributors/thread-distributor.js]: updated
