### PR TITLE
bug fix

### LINKED ISSUE #455: Cannot read property 'buffer' of null
## Describe the Bug

Cannot read property 'buffer' of null

## Steps to Reproduce

Go to Jenkins, TerraHub API project, job #1748

## Expected Behavior

Definitely NOT below error:
```
[iam_cross_account] aws_iam_role_policy.iam_cross_account: Refreshing state... (ID: CrossAccountRoleForThubProxy:CrossAccountPolicyForThubProxy)

❌ Worker error: "Cannot read property 'buffer' of null"

(node:29631) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: channel closed
(node:29678) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: channel closed
```

### PR DESCRIPTION
**Pull request by KanoniPan**
## Description

Fixes #455 

## Type of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/helpers/terrahub.js [hunk 1]
```diff
@@ -167,7 +167,7 @@ class Terrahub {
    */
   _getTask() {
     return this._on('start')
-      .then(() => this._hook('before'))
+      .then(() => this._hook('before', {}))
```
Comment (eistrati) [inline src/helpers/terrahub.js]: why before hook accepts default value as `{}` while after hook - `res`?

Comment (eistrati) [reply src/helpers/terrahub.js]: I think this line should look like this: `.then(res => this._hook('before', res))`. Does this make sense?
