### PR TITLE
fix output message in import action

### LINKED ISSUE #773: Output message for terrahub import is broken after refactoring
## Describe the Bug

Output message for terrahub import is broken after refactoring

## To Reproduce

Run `terrahub import -i [component_name] -c [key]=[value]`

## Expected Behavior

No issues are expected. Instead, we get the following broken message:
```
[ [ { type: 'Buffer', data: [Array] } ] ]
```

### PR DESCRIPTION
**Pull request by const-andreyLu**
## Description

Fixes #773 

## Type of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] This change requires a change to the documentation

## How Has This Been Tested?

- [x] terrahub import -i [component_name] -c [key]=[value]
- [x] terrahub run 

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have checked that my changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: src/helpers/util.js [hunk 1]
```diff
@@ -234,7 +234,7 @@ class Util {
     return promise.then(() => Buffer.concat(stdout)).catch(err => {
       err.message = Buffer.concat(stderr).toString();
 
-      return Promise.reject(err);
+      return Promise.reject('Error occurred.');
```
Comment (eistrati) [inline src/helpers/util.js]: please refactor this line to show the actual error when `DEBUG=debug`
